CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename TEXT NOT NULL,
  sha256 TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  version TEXT,
  status TEXT NOT NULL DEFAULT 'processing',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  r2_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS document_chunks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  page_number INTEGER,
  section TEXT,
  product_model TEXT,
  product_category TEXT,
  language TEXT NOT NULL DEFAULT 'und',
  document_version TEXT,
  source_type TEXT NOT NULL DEFAULT 'official_manual',
  embedding_model TEXT,
  vector_id TEXT UNIQUE,
  content TEXT NOT NULL,
  embedding vector(2048)
);
CREATE TABLE IF NOT EXISTS product_attributes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  attribute_key TEXT NOT NULL,
  value JSONB NOT NULL,
  unit TEXT,
  source_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  source_page INTEGER,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 1),
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  verified_by TEXT,
  verified_at TIMESTAMPTZ,
  UNIQUE(product_id, attribute_key)
);
CREATE TABLE IF NOT EXISTS features (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_key TEXT NOT NULL UNIQUE,
  canonical_name TEXT NOT NULL,
  category TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS feature_aliases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id INTEGER NOT NULL REFERENCES features(id) ON DELETE CASCADE,
  language TEXT NOT NULL,
  alias TEXT NOT NULL,
  UNIQUE(feature_id, language, alias)
);
CREATE TABLE IF NOT EXISTS product_features (
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  feature_id INTEGER NOT NULL REFERENCES features(id) ON DELETE CASCADE,
  source_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  source_page INTEGER,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 1),
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY(product_id, feature_id)
);
CREATE TABLE IF NOT EXISTS verified_facts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  predicate TEXT NOT NULL,
  value_json JSONB NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  verified_by TEXT,
  verified_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  intent TEXT NOT NULL,
  normalized_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  answer_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  query_language TEXT NOT NULL DEFAULT 'und',
  retrieval_trace_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 1),
  status TEXT NOT NULL DEFAULT 'answered',
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  filename TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMPTZ,
  total_records INTEGER NOT NULL DEFAULT 0,
  inserted_records INTEGER NOT NULL DEFAULT 0,
  updated_records INTEGER NOT NULL DEFAULT 0,
  failed_records INTEGER NOT NULL DEFAULT 0,
  skipped_records INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'running',
  error_message TEXT
);
CREATE TABLE IF NOT EXISTS support_cases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL DEFAULT 'telegram',
  source_chat TEXT,
  external_thread_id TEXT NOT NULL,
  date_start TIMESTAMPTZ,
  date_end TIMESTAMPTZ,
  root_author TEXT,
  root_question TEXT,
  message_count INTEGER NOT NULL DEFAULT 0,
  participants JSONB NOT NULL DEFAULT '[]'::jsonb,
  models JSONB NOT NULL DEFAULT '[]'::jsonb,
  domain_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  intent_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  media JSONB NOT NULL DEFAULT '[]'::jsonb,
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  verification_status TEXT NOT NULL DEFAULT 'unverified_candidate',
  production_answer_allowed BOOLEAN NOT NULL DEFAULT FALSE CHECK(production_answer_allowed IN (FALSE, TRUE)),
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processing_status TEXT NOT NULL DEFAULT 'pending',
  content_hash TEXT,
  import_batch_id INTEGER REFERENCES import_batches(id),
  UNIQUE(source, external_thread_id)
);
CREATE TABLE IF NOT EXISTS support_case_analysis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE CASCADE,
  source_content_hash TEXT NOT NULL,
  canonical_question TEXT NOT NULL,
  question_quality TEXT NOT NULL,
  domain TEXT NOT NULL,
  knowledge_type TEXT NOT NULL,
  models_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  products_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  features_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  symptoms_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  error_codes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  secondary_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  extraction_confidence DOUBLE PRECISION NOT NULL CHECK(extraction_confidence BETWEEN 0 AND 1),
  llm_provider TEXT NOT NULL,
  llm_model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  extracted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  ,UNIQUE(support_case_id, prompt_version)
);
CREATE TABLE IF NOT EXISTS support_case_analysis_failures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE CASCADE,
  source_content_hash TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  error_type TEXT NOT NULL,
  error_message TEXT NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(support_case_id, prompt_version)
);

CREATE TABLE IF NOT EXISTS topic_candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_candidate_id TEXT NOT NULL UNIQUE,
  frequency INTEGER NOT NULL CHECK(frequency > 0),
  representative_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE RESTRICT,
  representative_question TEXT NOT NULL,
  domain_distribution JSONB NOT NULL DEFAULT '{}'::jsonb,
  knowledge_type_distribution JSONB NOT NULL DEFAULT '{}'::jsonb,
  models JSONB NOT NULL DEFAULT '[]'::jsonb,
  cluster_min_similarity DOUBLE PRECISION NOT NULL CHECK(cluster_min_similarity BETWEEN -1 AND 1),
  cluster_mean_similarity DOUBLE PRECISION NOT NULL CHECK(cluster_mean_similarity BETWEEN -1 AND 1),
  taxonomy_mixed BOOLEAN NOT NULL DEFAULT FALSE,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK(review_status IN ('pending', 'approved', 'split_required', 'merge_required', 'rejected')),
  review_note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS topic_candidate_cases (
  topic_candidate_id TEXT NOT NULL REFERENCES topic_candidates(topic_candidate_id) ON DELETE CASCADE,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE CASCADE,
  PRIMARY KEY(topic_candidate_id, support_case_id)
);

CREATE TABLE IF NOT EXISTS topic_abstractions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL UNIQUE REFERENCES support_cases(id) ON DELETE CASCADE,
  analysis_id INTEGER NOT NULL REFERENCES support_case_analysis(id) ON DELETE RESTRICT,
  source_content_hash TEXT NOT NULL,
  canonical_question TEXT NOT NULL,
  topic_signature TEXT NOT NULL,
  model TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS topic_abstraction_failures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL UNIQUE REFERENCES support_cases(id) ON DELETE CASCADE,
  analysis_id INTEGER NOT NULL REFERENCES support_case_analysis(id) ON DELETE RESTRICT,
  source_content_hash TEXT NOT NULL,
  model TEXT NOT NULL,
  error_message TEXT NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS local_model_eval_runs (
  run_id TEXT PRIMARY KEY,
  mode TEXT NOT NULL DEFAULT 'smoke'
    CHECK (mode IN ('smoke', 'golden', 'benchmark')),
  sample_count INTEGER NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
  model_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'failed')),
  error_message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS local_model_eval_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES local_model_eval_runs(run_id) ON DELETE CASCADE,
  model_name TEXT NOT NULL,
  model_path TEXT NOT NULL,
  quantization TEXT NOT NULL DEFAULT '',
  sample_key TEXT NOT NULL,
  source_candidate_id TEXT,
  expected_verified_knowledge_id BIGINT REFERENCES verified_knowledge(verified_knowledge_id) ON DELETE SET NULL,
  question TEXT NOT NULL,
  expected_answer_status TEXT NOT NULL DEFAULT 'answered',
  expected_scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  expected_answer TEXT NOT NULL DEFAULT '',
  retrieved_verified_knowledge_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  retrieval_mode TEXT NOT NULL DEFAULT '',
  retrieval_hit_at_5 BOOLEAN,
  retrieval_hit_at_10 BOOLEAN,
  prompt_sha256 TEXT NOT NULL DEFAULT '',
  answer_text TEXT NOT NULL DEFAULT '',
  actual_answer_status TEXT NOT NULL DEFAULT 'service_error',
  actual_source_indexes JSONB NOT NULL DEFAULT '[]'::jsonb,
  structure_pass BOOLEAN,
  applicability_pass BOOLEAN,
  answer_pass BOOLEAN,
  reviewer_verdict TEXT NOT NULL DEFAULT 'pending'
    CHECK (reviewer_verdict IN ('pending', 'pass', 'fail', 'not_applicable')),
  reviewer_note TEXT NOT NULL DEFAULT '',
  raw_response TEXT NOT NULL DEFAULT '',
  error_message TEXT NOT NULL DEFAULT '',
  model_load_ms INTEGER,
  generation_ms INTEGER,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  tokens_per_second DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(run_id, model_name, sample_key)
);

CREATE INDEX IF NOT EXISTS ix_products_model ON products(model);
CREATE INDEX IF NOT EXISTS ix_documents_status ON documents(status);
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS ix_document_chunks_product_model ON document_chunks(product_model);
CREATE INDEX IF NOT EXISTS ix_document_chunks_language ON document_chunks(language);
CREATE INDEX IF NOT EXISTS ix_product_attributes_product_id ON product_attributes(product_id);
CREATE INDEX IF NOT EXISTS ix_feature_aliases_alias ON feature_aliases(alias);
CREATE INDEX IF NOT EXISTS ix_verified_facts_product_id ON verified_facts(product_id);
CREATE INDEX IF NOT EXISTS ix_questions_status ON questions(status);
CREATE INDEX IF NOT EXISTS ix_support_cases_verification ON support_cases(verification_status);
CREATE INDEX IF NOT EXISTS ix_support_cases_processing_status ON support_cases(processing_status);
CREATE INDEX IF NOT EXISTS ix_support_cases_import_batch_id ON support_cases(import_batch_id);
CREATE INDEX IF NOT EXISTS ix_support_case_analysis_case ON support_case_analysis(support_case_id);
CREATE INDEX IF NOT EXISTS ix_topic_candidates_frequency ON topic_candidates(frequency DESC);
CREATE INDEX IF NOT EXISTS ix_topic_candidate_cases_case ON topic_candidate_cases(support_case_id);
CREATE INDEX IF NOT EXISTS ix_topic_abstractions_source_hash ON topic_abstractions(source_content_hash);
CREATE INDEX IF NOT EXISTS ix_topic_abstraction_failures_case ON topic_abstraction_failures(support_case_id);
CREATE INDEX IF NOT EXISTS ix_document_chunks_content_fts ON document_chunks USING gin(to_tsvector('simple', content || ' ' || coalesce(product_model, '')));
CREATE INDEX IF NOT EXISTS ix_local_model_eval_results_run ON local_model_eval_results(run_id, model_name);
CREATE INDEX IF NOT EXISTS ix_local_model_eval_results_vk ON local_model_eval_results(expected_verified_knowledge_id);
