-- Review-only workflow for Verified Knowledge candidates.
-- This migration is additive and does not alter or delete source tables.

CREATE TABLE IF NOT EXISTS verified_knowledge_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL UNIQUE,
  knowledge_key TEXT NOT NULL,
  title TEXT NOT NULL,
  knowledge_type TEXT NOT NULL DEFAULT 'other',
  scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  question_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
  claims JSONB NOT NULL DEFAULT '[]'::jsonb,
  procedure_steps JSONB NOT NULL DEFAULT '[]'::jsonb,
  conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  exceptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence TEXT NOT NULL DEFAULT 'low' CHECK (confidence IN ('low', 'medium', 'high')),
  freshness_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
  last_verified_at TIMESTAMPTZ,
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status = 'pending'),
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'corrected', 'approved', 'needs_engineer', 'rejected', 'duplicate')),
  review_note TEXT NOT NULL DEFAULT '',
  reject_reason TEXT,
  reviewer TEXT,
  reviewed_at TIMESTAMPTZ,
  duplicate_of TEXT REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE SET NULL,
  split_from_candidate_id TEXT REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE SET NULL,
  publication_status TEXT NOT NULL DEFAULT 'draft' CHECK (publication_status IN ('draft', 'published')),
  production_answer_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  frequency INTEGER NOT NULL DEFAULT 0 CHECK (frequency >= 0),
  ai_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  human_overrides JSONB NOT NULL DEFAULT '{}'::jsonb,
  effective_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS verified_knowledge_candidate_cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE RESTRICT,
  case_position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(candidate_id, support_case_id)
);

CREATE TABLE IF NOT EXISTS verified_knowledge_candidate_message_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE RESTRICT,
  message_index INTEGER NOT NULL,
  ai_role TEXT NOT NULL CHECK (ai_role IN ('user_report', 'engineer_hypothesis', 'engineer_instruction', 'observed_result', 'confirmed_resolution', 'unconfirmed_claim', 'irrelevant')),
  human_role TEXT CHECK (human_role IS NULL OR human_role IN ('user_report', 'engineer_hypothesis', 'engineer_instruction', 'observed_result', 'confirmed_resolution', 'unconfirmed_claim', 'irrelevant')),
  effective_role TEXT NOT NULL CHECK (effective_role IN ('user_report', 'engineer_hypothesis', 'engineer_instruction', 'observed_result', 'confirmed_resolution', 'unconfirmed_claim', 'irrelevant')),
  ai_reason TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(candidate_id, support_case_id, message_index)
);

CREATE TABLE IF NOT EXISTS verified_knowledge_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  claim_position INTEGER NOT NULL,
  ai_claim JSONB NOT NULL DEFAULT '{}'::jsonb,
  human_claim JSONB,
  effective_claim JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(candidate_id, claim_position)
);

CREATE TABLE IF NOT EXISTS verified_knowledge_candidate_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  evidence_id TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'official_document',
  document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  document_title TEXT NOT NULL DEFAULT '',
  page INTEGER,
  chunk_id INTEGER,
  excerpt TEXT NOT NULL DEFAULT '',
  ai_evidence_relation TEXT NOT NULL DEFAULT 'unreviewed' CHECK (ai_evidence_relation IN ('supports', 'partial', 'irrelevant', 'conflict', 'unreviewed')),
  human_evidence_relation TEXT CHECK (human_evidence_relation IS NULL OR human_evidence_relation IN ('supports', 'partial', 'irrelevant', 'conflict', 'unreviewed')),
  effective_evidence_relation TEXT NOT NULL DEFAULT 'unreviewed' CHECK (effective_evidence_relation IN ('supports', 'partial', 'irrelevant', 'conflict', 'unreviewed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(candidate_id, evidence_id)
);

CREATE TABLE IF NOT EXISTS knowledge_review_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  support_case_id INTEGER REFERENCES support_cases(id) ON DELETE SET NULL,
  reviewer TEXT NOT NULL DEFAULT 'internal-reviewer',
  event_type TEXT NOT NULL,
  field_name TEXT,
  ai_value JSONB,
  old_value JSONB,
  new_value JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_learning_examples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  example_type TEXT NOT NULL CHECK (example_type IN (
    'intent_correction', 'knowledge_key_correction', 'model_extraction_correction',
    'scope_correction', 'claim_correction', 'telegram_role_correction',
    'evidence_correction', 'positive_example', 'negative_example'
  )),
  input_text TEXT NOT NULL DEFAULT '',
  ai_output JSONB NOT NULL DEFAULT '{}'::jsonb,
  human_output JSONB NOT NULL DEFAULT '{}'::jsonb,
  knowledge_key TEXT,
  support_case_id INTEGER REFERENCES support_cases(id) ON DELETE SET NULL,
  candidate_id TEXT REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE SET NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_for_reuse BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS knowledge_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concept TEXT NOT NULL,
  alias TEXT NOT NULL,
  created_by TEXT NOT NULL DEFAULT 'internal-reviewer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(concept, alias)
);

CREATE TABLE IF NOT EXISTS verified_knowledge (
  verified_knowledge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_key TEXT NOT NULL,
  title TEXT NOT NULL,
  knowledge_type TEXT NOT NULL DEFAULT 'other',
  scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  claims JSONB NOT NULL DEFAULT '[]'::jsonb,
  conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  exceptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  question_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE RESTRICT,
  verified_by TEXT NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  publication_status TEXT NOT NULL DEFAULT 'draft' CHECK (publication_status IN ('draft', 'published')),
  production_answer_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(source_candidate_id)
);

CREATE INDEX IF NOT EXISTS ix_review_candidates_status ON verified_knowledge_candidates(review_status);
CREATE INDEX IF NOT EXISTS ix_review_candidates_key ON verified_knowledge_candidates(knowledge_key);
CREATE INDEX IF NOT EXISTS ix_review_candidates_frequency ON verified_knowledge_candidates(frequency DESC);
CREATE INDEX IF NOT EXISTS ix_review_candidate_cases_case ON verified_knowledge_candidate_cases(support_case_id);
CREATE INDEX IF NOT EXISTS ix_review_message_roles_case ON verified_knowledge_candidate_message_roles(support_case_id);
CREATE INDEX IF NOT EXISTS ix_review_evidence_candidate ON verified_knowledge_candidate_evidence(candidate_id);
CREATE INDEX IF NOT EXISTS ix_review_events_candidate_created ON knowledge_review_events(candidate_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_learning_examples_type ON knowledge_learning_examples(example_type, approved_for_reuse);
CREATE UNIQUE INDEX IF NOT EXISTS ux_knowledge_aliases_concept_alias_ci ON knowledge_aliases(concept, lower(alias));
CREATE INDEX IF NOT EXISTS ix_verified_knowledge_key ON verified_knowledge(knowledge_key);
