-- MVP RAG orchestration and traceable historical case memory.
-- Unreviewed case memory may be used as an AI-derived answer source, but must
-- remain visibly distinct from human-approved Verified Knowledge.

ALTER TABLE knowledge_aliases
  ADD COLUMN IF NOT EXISTS knowledge_key TEXT,
  ADD COLUMN IF NOT EXISTS support_case_id INTEGER REFERENCES support_cases(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS approved_for_reuse BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS ix_knowledge_aliases_key
  ON knowledge_aliases(knowledge_key, lower(alias));
CREATE INDEX IF NOT EXISTS ix_knowledge_aliases_case
  ON knowledge_aliases(support_case_id);

ALTER TABLE knowledge_learning_examples
  ADD COLUMN IF NOT EXISTS searchable_text TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS embedding vector(1024),
  ADD COLUMN IF NOT EXISTS embedding_model TEXT;

UPDATE knowledge_learning_examples
SET searchable_text = left(concat_ws(' ', input_text, knowledge_key, human_output::text), 30000)
WHERE searchable_text='';

CREATE INDEX IF NOT EXISTS ix_learning_examples_approved_type
  ON knowledge_learning_examples(example_type, approved_for_reuse, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_learning_examples_embedding_hnsw
  ON knowledge_learning_examples USING hnsw(embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS ix_learning_examples_searchable_fts
  ON knowledge_learning_examples USING gin(to_tsvector('simple', searchable_text));

CREATE TABLE IF NOT EXISTS case_knowledge_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL UNIQUE REFERENCES support_cases(id) ON DELETE CASCADE,
  source_candidate_id TEXT REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE SET NULL,
  knowledge_key TEXT NOT NULL,
  canonical_question TEXT NOT NULL DEFAULT '',
  knowledge_type TEXT NOT NULL DEFAULT 'other',
  scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  question_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
  answer_text TEXT NOT NULL DEFAULT '',
  claims JSONB NOT NULL DEFAULT '[]'::jsonb,
  procedure_steps JSONB NOT NULL DEFAULT '[]'::jsonb,
  conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  exceptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_status TEXT NOT NULL DEFAULT 'ai_derived'
    CHECK (source_status IN ('ai_derived', 'verified', 'needs_context', 'conflict', 'rejected')),
  answer_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  requires_context BOOLEAN NOT NULL DEFAULT FALSE,
  source_confidence DOUBLE PRECISION NOT NULL DEFAULT 0
    CHECK (source_confidence BETWEEN 0 AND 1),
  searchable_text TEXT NOT NULL DEFAULT '',
  embedding vector(1024),
  embedding_model TEXT,
  source_content_hash TEXT,
  last_verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_case_memory_status
  ON case_knowledge_memory(source_status, answer_allowed, requires_context);
CREATE INDEX IF NOT EXISTS ix_case_memory_key
  ON case_knowledge_memory(knowledge_key);
CREATE INDEX IF NOT EXISTS ix_case_memory_embedding_hnsw
  ON case_knowledge_memory USING hnsw(embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS ix_case_memory_searchable_fts
  ON case_knowledge_memory USING gin(to_tsvector('simple', searchable_text));
