-- Persisted semantic review groups.  Groups are review proposals until the
-- reviewer explicitly saves membership and approves the aggregate candidate.

ALTER TABLE verified_knowledge_candidates
  ADD COLUMN IF NOT EXISTS merged_into_group_id TEXT;

ALTER TABLE verified_knowledge_candidates
  DROP CONSTRAINT IF EXISTS verified_knowledge_candidates_review_status_check;
ALTER TABLE verified_knowledge_candidates
  ADD CONSTRAINT verified_knowledge_candidates_review_status_check
  CHECK (review_status IN ('pending', 'corrected', 'approved', 'needs_engineer', 'rejected', 'duplicate', 'merged'));

ALTER TABLE verified_knowledge_candidates
  DROP CONSTRAINT IF EXISTS verified_knowledge_candidates_answer_status_check;
ALTER TABLE verified_knowledge_candidates
  ADD CONSTRAINT verified_knowledge_candidates_answer_status_check
  CHECK (answer_status IN ('pending', 'approved', 'needs_context', 'rejected', 'duplicate', 'merged'));

CREATE TABLE IF NOT EXISTS knowledge_review_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id TEXT NOT NULL UNIQUE,
  canonical_candidate_id TEXT NOT NULL UNIQUE
    REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'published', 'cancelled')),
  algorithm_version TEXT NOT NULL DEFAULT 'bge-m3-review-groups-v1',
  similarity_threshold NUMERIC(6,5) NOT NULL DEFAULT 0.76000,
  draft_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  conflict_summary JSONB NOT NULL DEFAULT '[]'::jsonb,
  reviewer TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_review_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id TEXT NOT NULL REFERENCES knowledge_review_groups(group_id) ON DELETE CASCADE,
  candidate_id TEXT NOT NULL REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE RESTRICT,
  membership_status TEXT NOT NULL DEFAULT 'included'
    CHECK (membership_status IN ('included', 'excluded')),
  similarity_score NUMERIC(8,6),
  source TEXT NOT NULL DEFAULT 'auto'
    CHECK (source IN ('auto', 'manual')),
  exclusion_reason TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(group_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS knowledge_review_group_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id TEXT NOT NULL REFERENCES knowledge_review_groups(group_id) ON DELETE CASCADE,
  fact_type TEXT NOT NULL,
  fact_key TEXT NOT NULL,
  fact_value JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_candidate_id TEXT REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE SET NULL,
  support_case_id INTEGER REFERENCES support_cases(id) ON DELETE SET NULL,
  selected BOOLEAN NOT NULL DEFAULT TRUE,
  conflict BOOLEAN NOT NULL DEFAULT FALSE,
  exclusion_reason TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_candidate_embeddings (
  candidate_id TEXT PRIMARY KEY REFERENCES verified_knowledge_candidates(candidate_id) ON DELETE CASCADE,
  embedding vector(1024) NOT NULL,
  embedding_model TEXT NOT NULL,
  source_hash TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_review_groups_status ON knowledge_review_groups(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_review_group_members_candidate ON knowledge_review_group_members(candidate_id, membership_status);
CREATE INDEX IF NOT EXISTS ix_review_group_facts_group ON knowledge_review_group_facts(group_id, fact_type, selected);
CREATE INDEX IF NOT EXISTS ix_review_candidates_merged_group ON verified_knowledge_candidates(merged_into_group_id);
