-- Preserve Telegram message provenance and make human publication independent
-- from the OpenRouter embedding service.

CREATE TABLE IF NOT EXISTS message_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_case_id INTEGER NOT NULL REFERENCES support_cases(id) ON DELETE CASCADE,
  source_message_id TEXT NOT NULL,
  target_message_id TEXT NOT NULL,
  relation_type TEXT NOT NULL CHECK (relation_type IN ('answers', 'confirm_success', 'confirm_failure', 'reply_to')),
  source TEXT NOT NULL CHECK (source IN ('manual', 'telegram', 'inferred')),
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(support_case_id, source_message_id, target_message_id, relation_type)
);

CREATE INDEX IF NOT EXISTS ix_message_relations_case
  ON message_relations(support_case_id, source_message_id, target_message_id);
CREATE INDEX IF NOT EXISTS ix_message_relations_target
  ON message_relations(target_message_id, relation_type);

CREATE TABLE IF NOT EXISTS knowledge_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_id BIGINT NOT NULL REFERENCES verified_knowledge(verified_knowledge_id) ON DELETE CASCADE,
  source_type TEXT NOT NULL CHECK (source_type IN ('telegram', 'telegram_message', 'official_document', 'product_fact', 'structured_fact', 'inventory')),
  case_id INTEGER REFERENCES support_cases(id) ON DELETE SET NULL,
  message_id TEXT,
  evidence_role TEXT NOT NULL CHECK (evidence_role IN ('supports', 'confirmed_success', 'confirmed_failure', 'context_only')),
  evidence_status TEXT NOT NULL CHECK (evidence_status IN ('supports', 'confirmed_success', 'confirmed_failure', 'context_only')),
  excerpt TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_knowledge_evidence_identity
  ON knowledge_evidence(knowledge_id, source_type, COALESCE(case_id, 0), COALESCE(message_id, ''));
CREATE INDEX IF NOT EXISTS ix_knowledge_evidence_knowledge
  ON knowledge_evidence(knowledge_id, evidence_status);
CREATE INDEX IF NOT EXISTS ix_knowledge_evidence_case
  ON knowledge_evidence(case_id, message_id);

ALTER TABLE verified_knowledge
  ADD COLUMN IF NOT EXISTS embedding_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS embedding_error TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS embedding_updated_at TIMESTAMPTZ;

UPDATE verified_knowledge
SET embedding_status = CASE WHEN embedding IS NULL THEN 'pending' ELSE 'ready' END,
    embedding_updated_at = CASE WHEN embedding IS NULL THEN embedding_updated_at ELSE COALESCE(embedding_updated_at, updated_at) END
;

ALTER TABLE verified_knowledge
  DROP CONSTRAINT IF EXISTS verified_knowledge_embedding_status_check;
ALTER TABLE verified_knowledge
  ADD CONSTRAINT verified_knowledge_embedding_status_check
  CHECK (embedding_status IN ('pending', 'ready', 'failed'));
