-- Evaluation-only storage for local Qwen model comparisons.
-- This migration must not alter production answer or knowledge state.

CREATE TABLE IF NOT EXISTS local_model_eval_runs (
  run_id TEXT PRIMARY KEY,
  mode TEXT NOT NULL DEFAULT 'smoke'
    CHECK (mode IN ('smoke', 'golden', 'benchmark')),
  sample_count INTEGER NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
  model_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_path TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'failed')),
  error_message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS local_model_eval_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES local_model_eval_runs(run_id) ON DELETE CASCADE,
  model_name TEXT NOT NULL,
  model_path TEXT NOT NULL,
  quantization TEXT NOT NULL DEFAULT '',
  sample_key TEXT NOT NULL,
  source_candidate_id TEXT,
  expected_verified_knowledge_id BIGINT REFERENCES verified_knowledge(verified_knowledge_id) ON DELETE SET NULL,
  question TEXT NOT NULL,
  expected_answer_status TEXT NOT NULL DEFAULT 'answered',
  expected_scope JSONB NOT NULL DEFAULT '{}'::jsonb,
  expected_answer TEXT NOT NULL DEFAULT '',
  retrieved_verified_knowledge_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  retrieval_mode TEXT NOT NULL DEFAULT '',
  retrieval_hit_at_5 BOOLEAN,
  retrieval_hit_at_10 BOOLEAN,
  prompt_sha256 TEXT NOT NULL DEFAULT '',
  answer_text TEXT NOT NULL DEFAULT '',
  actual_answer_status TEXT NOT NULL DEFAULT 'service_error',
  actual_source_indexes JSONB NOT NULL DEFAULT '[]'::jsonb,
  structure_pass BOOLEAN,
  applicability_pass BOOLEAN,
  answer_pass BOOLEAN,
  reviewer_verdict TEXT NOT NULL DEFAULT 'pending'
    CHECK (reviewer_verdict IN ('pending', 'pass', 'fail', 'not_applicable')),
  reviewer_note TEXT NOT NULL DEFAULT '',
  raw_response TEXT NOT NULL DEFAULT '',
  error_message TEXT NOT NULL DEFAULT '',
  model_load_ms INTEGER,
  generation_ms INTEGER,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  tokens_per_second DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(run_id, model_name, sample_key)
);

CREATE INDEX IF NOT EXISTS ix_local_model_eval_results_run
  ON local_model_eval_results(run_id, model_name);
CREATE INDEX IF NOT EXISTS ix_local_model_eval_results_vk
  ON local_model_eval_results(expected_verified_knowledge_id);
