-- V2 skeleton: additive, minimal data model for Inbox-first learning.
--
-- This migration deliberately does not alter or depend on V1 review/publish
-- tables.  Raw evidence is immutable input; internalized knowledge is a
-- separate object; knowledge_sources preserves the provenance between them.
--
-- V2 trust is intentionally limited to these four values:
--   official_source, user_confirmed, provisional, conflicted
-- Only official_source and user_confirmed may later pass a customer-answer
-- retrieval gate.  The gate is application behavior; this migration keeps
-- the trust vocabulary closed at the database boundary.
-- Every table and index declaration is guarded with IF NOT EXISTS, so rerunning
-- this file is harmless.  apply_migration.py also records its content checksum.

-- Original material must remain available even after an AI summary or a
-- Knowledge record is created.  One row represents one captured source item.
CREATE TABLE IF NOT EXISTS v2_raw_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_type TEXT NOT NULL CHECK (evidence_type IN (
    'telegram', 'user_input', 'document', 'spreadsheet', 'faq', 'other'
  )),
  author_role TEXT NOT NULL DEFAULT 'unknown' CHECK (author_role IN (
    'customer', 'product_expert', 'assistant', 'system', 'unknown'
  )),
  content TEXT NOT NULL DEFAULT '',
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_label TEXT NOT NULL DEFAULT '',
  source_locator TEXT NOT NULL DEFAULT '',
  external_id TEXT,
  conversation_id TEXT,
  document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  document_chunk_id INTEGER REFERENCES document_chunks(id) ON DELETE SET NULL,
  telegram_chat_id TEXT,
  telegram_message_id TEXT,
  reply_to_telegram_message_id TEXT,
  evidence_status TEXT NOT NULL DEFAULT 'active' CHECK (evidence_status IN (
    'active', 'superseded', 'redacted'
  )),
  captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (evidence_type, external_id)
);

COMMENT ON TABLE v2_raw_evidence IS
  'V2 immutable-ish raw inputs; never replace source text with an AI summary.';
COMMENT ON COLUMN v2_raw_evidence.raw_payload IS
  'Original structured payload, such as a Telegram update or imported row.';
COMMENT ON COLUMN v2_raw_evidence.source_locator IS
  'Human-readable provenance locator, such as a PDF page or Telegram message link.';

-- The only internalized V2 knowledge object.  It intentionally has no V1
-- review fields, range hierarchy, or publication workflow fields.
CREATE TABLE IF NOT EXISTS v2_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  entity_name TEXT NOT NULL DEFAULT '',
  trust TEXT NOT NULL CHECK (trust IN (
    'official_source', 'user_confirmed', 'provisional', 'conflicted'
  )),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE v2_knowledge IS
  'Minimal V2 internalized knowledge; only explicitly allowed trust values exist.';
COMMENT ON COLUMN v2_knowledge.trust IS
  'official_source/user_confirmed are answer-eligible; provisional/conflicted are not.';
COMMENT ON COLUMN v2_knowledge.active IS
  'Inactive knowledge remains auditable but must be excluded from production retrieval.';

-- A source relationship is separate so every Knowledge item remains traceable
-- to the raw evidence and rejected/conflicting evidence is never destroyed.
CREATE TABLE IF NOT EXISTS v2_knowledge_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_id BIGINT NOT NULL REFERENCES v2_knowledge(id) ON DELETE CASCADE,
  raw_evidence_id BIGINT NOT NULL REFERENCES v2_raw_evidence(id) ON DELETE RESTRICT,
  source_kind TEXT NOT NULL CHECK (source_kind IN (
    'official_document', 'user_confirmation', 'user_input', 'telegram',
    'spreadsheet', 'faq', 'other'
  )),
  relation TEXT NOT NULL CHECK (relation IN (
    'supports', 'contradicts', 'context'
  )),
  source_role TEXT NOT NULL CHECK (source_role IN (
    'primary', 'supporting', 'contradicting', 'context'
  )),
  excerpt TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  resolution TEXT NOT NULL DEFAULT 'unresolved' CHECK (resolution IN (
    'unresolved', 'accepted', 'rejected', 'superseded'
  )),
  CHECK (
    (active AND resolution IN ('unresolved', 'accepted'))
    OR (NOT active AND resolution IN ('rejected', 'superseded'))
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (knowledge_id, raw_evidence_id, relation)
);

COMMENT ON TABLE v2_knowledge_sources IS
  'Provenance links from internalized Knowledge to original evidence, including rejected evidence.';
COMMENT ON COLUMN v2_knowledge_sources.active IS
  'Set false when evidence is rejected or superseded; do not delete the audit trail.';
COMMENT ON COLUMN v2_knowledge_sources.resolution IS
  'Conflict decisions are represented here without inventing a fifth trust value.';

-- Inbox is the user-facing conversation boundary for learning and later Grill
-- sessions.  A thread can also retain the origin of a Telegram conversation.
CREATE TABLE IF NOT EXISTS v2_inbox_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_type TEXT NOT NULL DEFAULT 'learning' CHECK (thread_type IN (
    'learning', 'grill', 'customer_refusal', 'general'
  )),
  origin TEXT NOT NULL DEFAULT 'web' CHECK (origin IN (
    'web', 'telegram', 'import', 'system'
  )),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
    'open', 'paused', 'completed', 'archived'
  )),
  external_thread_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE v2_inbox_threads IS
  'Chat-style Inbox conversation; technical knowledge fields are intentionally absent.';

-- Messages preserve the conversational UX and can point back to the exact raw
-- input that caused the turn.  A message has one explicit role, never an
-- inferred review role.
CREATE TABLE IF NOT EXISTS v2_inbox_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES v2_inbox_threads(id) ON DELETE CASCADE,
  sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN (
    'text', 'question', 'proposal', 'confirmation', 'correction',
    'skip', 'unknown', 'summary', 'evidence'
  )),
  content TEXT NOT NULL DEFAULT '',
  raw_evidence_id BIGINT REFERENCES v2_raw_evidence(id) ON DELETE RESTRICT,
  message_status TEXT NOT NULL DEFAULT 'active' CHECK (message_status IN (
    'active', 'superseded'
  )),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (thread_id, sequence_no)
);

COMMENT ON TABLE v2_inbox_messages IS
  'Ordered Inbox messages with explicit chat roles and optional raw-evidence provenance.';

-- A proposal is one atomic fact/question at a time.  Confirmation state is
-- separate from Knowledge trust so an unconfirmed proposal cannot silently
-- become user_confirmed.
CREATE TABLE IF NOT EXISTS v2_learning_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES v2_inbox_threads(id) ON DELETE CASCADE,
  source_message_id BIGINT REFERENCES v2_inbox_messages(id) ON DELETE SET NULL,
  question_message_id BIGINT REFERENCES v2_inbox_messages(id) ON DELETE SET NULL,
  fact_text TEXT NOT NULL,
  entity_name TEXT NOT NULL DEFAULT '',
  proposed_trust TEXT NOT NULL DEFAULT 'provisional' CHECK (proposed_trust IN (
    'official_source', 'user_confirmed', 'provisional', 'conflicted'
  )),
  status TEXT NOT NULL DEFAULT 'pending_confirmation' CHECK (status IN (
    'pending_confirmation', 'confirmed', 'corrected', 'skipped',
    'unknown', 'rejected', 'superseded'
  )),
  confirmed_knowledge_id BIGINT REFERENCES v2_knowledge(id) ON DELETE SET NULL,
  resolution_message_id BIGINT REFERENCES v2_inbox_messages(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status <> 'confirmed' OR confirmed_knowledge_id IS NOT NULL),
  CHECK (proposed_trust <> 'user_confirmed' OR status = 'confirmed')
);

COMMENT ON TABLE v2_learning_proposals IS
  'One atomic fact awaiting explicit user confirmation, correction, skip, or unknown response.';
COMMENT ON COLUMN v2_learning_proposals.proposed_trust IS
  'AI proposal classification only; it never grants user_confirmed trust by itself.';

-- Sessions track a learning interaction without exposing a review workflow.
-- Active Grill may continue asking; passive sessions can carry the default
-- daily question budget supplied by application configuration.
CREATE TABLE IF NOT EXISTS v2_learning_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES v2_inbox_threads(id) ON DELETE CASCADE,
  session_type TEXT NOT NULL DEFAULT 'passive' CHECK (session_type IN (
    'passive', 'active_grill'
  )),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
    'active', 'paused', 'completed', 'abandoned'
  )),
  question_budget INTEGER NOT NULL DEFAULT 5 CHECK (question_budget >= 0),
  questions_asked INTEGER NOT NULL DEFAULT 0 CHECK (questions_asked >= 0),
  summary TEXT NOT NULL DEFAULT '',
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (completed_at IS NULL OR status IN ('completed', 'abandoned'))
);

COMMENT ON TABLE v2_learning_sessions IS
  'Learning/Grill session state; question budget is configurable data, not scattered code.';

CREATE INDEX IF NOT EXISTS ix_v2_raw_evidence_type_status
  ON v2_raw_evidence(evidence_type, evidence_status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_v2_raw_evidence_external_thread
  ON v2_raw_evidence(conversation_id, captured_at);
CREATE INDEX IF NOT EXISTS ix_v2_knowledge_trust_active
  ON v2_knowledge(trust, active, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_v2_knowledge_entity
  ON v2_knowledge(entity_name);
CREATE INDEX IF NOT EXISTS ix_v2_knowledge_sources_knowledge
  ON v2_knowledge_sources(knowledge_id, active, relation);
CREATE INDEX IF NOT EXISTS ix_v2_knowledge_sources_raw
  ON v2_knowledge_sources(raw_evidence_id);
CREATE INDEX IF NOT EXISTS ix_v2_inbox_threads_status
  ON v2_inbox_threads(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_v2_inbox_messages_thread
  ON v2_inbox_messages(thread_id, sequence_no);
CREATE INDEX IF NOT EXISTS ix_v2_learning_proposals_status
  ON v2_learning_proposals(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_v2_learning_proposals_thread
  ON v2_learning_proposals(thread_id, status);
CREATE INDEX IF NOT EXISTS ix_v2_learning_sessions_status
  ON v2_learning_sessions(status, session_type, updated_at DESC);
