-- V2 Phase 2.1: additive long/bulk Inbox intake metadata.
-- Raw evidence remains the source of truth; a batch is only a small coverage
-- and confirmation envelope around the existing atomic proposals.

CREATE TABLE IF NOT EXISTS v2_learning_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES v2_inbox_threads(id) ON DELETE CASCADE,
  raw_evidence_id BIGINT NOT NULL REFERENCES v2_raw_evidence(id) ON DELETE RESTRICT,
  raw_source TEXT NOT NULL DEFAULT '',
  total_segments INTEGER NOT NULL CHECK (total_segments >= 0),
  processed_segments INTEGER NOT NULL DEFAULT 0 CHECK (processed_segments >= 0),
  failed_segments INTEGER NOT NULL DEFAULT 0 CHECK (failed_segments >= 0),
  clear_facts JSONB NOT NULL DEFAULT '[]'::jsonb,
  unclear_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  conflicts JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'processing' CHECK (status IN (
    'processing', 'awaiting_confirmation', 'awaiting_clarification',
    'partial', 'completed', 'failed'
  )),
  confirmation_message_id BIGINT REFERENCES v2_inbox_messages(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE v2_learning_proposals
  ADD COLUMN IF NOT EXISTS batch_id BIGINT REFERENCES v2_learning_batches(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS segment_no INTEGER,
  ADD COLUMN IF NOT EXISTS expected_answer_type TEXT NOT NULL DEFAULT 'free_text',
  ADD COLUMN IF NOT EXISTS derived BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS individual_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS paused BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE v2_learning_proposals
  DROP CONSTRAINT IF EXISTS v2_learning_proposals_answer_type_check;

ALTER TABLE v2_learning_proposals
  ADD CONSTRAINT v2_learning_proposals_answer_type_check CHECK (
    expected_answer_type IN ('binary', 'free_text')
  );

ALTER TABLE v2_inbox_messages
  DROP CONSTRAINT IF EXISTS v2_inbox_messages_message_type_check;

ALTER TABLE v2_inbox_messages
  ADD CONSTRAINT v2_inbox_messages_message_type_check CHECK (message_type IN (
    'text', 'question', 'clarification', 'batch_confirmation', 'proposal',
    'confirmation', 'correction', 'skip', 'unknown', 'summary', 'evidence'
  ));

CREATE INDEX IF NOT EXISTS ix_v2_learning_batches_thread_status
  ON v2_learning_batches(thread_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_v2_learning_proposals_batch
  ON v2_learning_proposals(batch_id, segment_no, status);
