-- Phase 2.1.1: durable, short-lived Inbox processing jobs.
--
-- This is deliberately only a job envelope around the existing V2 learning
-- loop.  It is not a workflow engine and does not alter V1 tables.

CREATE TABLE IF NOT EXISTS v2_inbox_processing_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES v2_inbox_threads(id) ON DELETE CASCADE,
  raw_evidence_id BIGINT NOT NULL REFERENCES v2_raw_evidence(id) ON DELETE RESTRICT,
  user_message_id BIGINT NOT NULL REFERENCES v2_inbox_messages(id) ON DELETE RESTRICT,
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN (
    'queued', 'processing', 'completed', 'failed'
  )),
  error_message TEXT,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_v2_inbox_processing_jobs_thread_status
  ON v2_inbox_processing_jobs(thread_id, status, id);

COMMENT ON TABLE v2_inbox_processing_jobs IS
  'Small durable envelope for asynchronous V2 Inbox learning; evidence remains the source of truth.';
