-- Phase 2.2: a small, additive organization layer for V2 knowledge.
--
-- Facts remain in v2_knowledge.  These tables only describe a deliberately
-- small, auditable tree around facts; they are not a graph or taxonomy.

CREATE TABLE IF NOT EXISTS v2_entities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN (
    'brand', 'category', 'product_line', 'series', 'model', 'concept'
  )),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (normalized_name)
);

COMMENT ON TABLE v2_entities IS
  'Small V2 organization layer; facts remain in v2_knowledge.';
COMMENT ON COLUMN v2_entities.normalized_name IS
  'Application-normalized exact-dedup key; it is not an alias registry.';

CREATE TABLE IF NOT EXISTS v2_entity_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_entity_id BIGINT NOT NULL REFERENCES v2_entities(id) ON DELETE RESTRICT,
  child_entity_id BIGINT NOT NULL REFERENCES v2_entities(id) ON DELETE RESTRICT,
  relation_type TEXT NOT NULL CHECK (relation_type IN ('belongs_to')),
  source_id BIGINT REFERENCES v2_knowledge(id) ON DELETE RESTRICT,
  provenance TEXT NOT NULL DEFAULT '',
  provenance_kind TEXT NOT NULL CHECK (provenance_kind IN (
    'official_source', 'user_confirmed', 'explicit_user_confirmation'
  )),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (parent_entity_id <> child_entity_id),
  CHECK (source_id IS NOT NULL OR char_length(btrim(provenance)) > 0)
);

COMMENT ON TABLE v2_entity_relations IS
  'Auditable local belongs_to relations; inactive rows preserve structural history.';
COMMENT ON COLUMN v2_entity_relations.source_id IS
  'Optional V2 knowledge provenance reference; formal relations still require provenance.';
COMMENT ON COLUMN v2_entity_relations.provenance_kind IS
  'Validated by the application against source Knowledge trust.';

CREATE UNIQUE INDEX IF NOT EXISTS ux_v2_entity_relations_active_pair
  ON v2_entity_relations(parent_entity_id, child_entity_id, relation_type)
  WHERE active = TRUE;

-- A belongs_to tree has at most one current parent per child.  Historical
-- moves remain possible because only active rows participate in this index.
CREATE UNIQUE INDEX IF NOT EXISTS ux_v2_entity_relations_active_child
  ON v2_entity_relations(child_entity_id, relation_type)
  WHERE active = TRUE;

CREATE INDEX IF NOT EXISTS ix_v2_entities_active_type
  ON v2_entities(active, entity_type, normalized_name);
CREATE INDEX IF NOT EXISTS ix_v2_entity_relations_child
  ON v2_entity_relations(child_entity_id, active, relation_type);
CREATE INDEX IF NOT EXISTS ix_v2_entity_relations_parent
  ON v2_entity_relations(parent_entity_id, active, relation_type);
CREATE INDEX IF NOT EXISTS ix_v2_entity_relations_source
  ON v2_entity_relations(source_id);

ALTER TABLE v2_knowledge
  ADD COLUMN IF NOT EXISTS entity_id BIGINT
  REFERENCES v2_entities(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_v2_knowledge_entity_id
  ON v2_knowledge(entity_id)
  WHERE entity_id IS NOT NULL;

-- Bounded, deterministic backfill for already explicit entity_name values.
-- This creates no parent relation and makes no alias or series inference:
-- whitespace/case normalization is the only identity rule.  Names containing
-- a model-like digit are displayed as models; other explicit names remain
-- unorganized concepts until later evidence provides structure.
WITH candidates AS (
  SELECT
    regexp_replace(lower(btrim(entity_name)), '[[:space:]]+', '', 'g') AS normalized_name,
    min(btrim(entity_name)) AS name,
    CASE WHEN bool_or(entity_name ~ '[0-9]') THEN 'model' ELSE 'concept' END AS entity_type
  FROM v2_knowledge
  WHERE active=TRUE AND char_length(btrim(entity_name)) > 0
  GROUP BY regexp_replace(lower(btrim(entity_name)), '[[:space:]]+', '', 'g')
)
INSERT INTO v2_entities(name, normalized_name, entity_type)
SELECT name, normalized_name, entity_type
FROM candidates
ON CONFLICT (normalized_name) DO NOTHING;

UPDATE v2_knowledge k
SET entity_id=e.id, updated_at=CURRENT_TIMESTAMP
FROM v2_entities e
WHERE k.entity_id IS NULL
  AND char_length(btrim(k.entity_name)) > 0
  AND e.normalized_name = regexp_replace(lower(btrim(k.entity_name)), '[[:space:]]+', '', 'g');
