-- Additive, compact audit snapshots for deterministic Knowledge maintenance.
-- Raw evidence and source links remain immutable; this table records only
-- changes made to the internalized Knowledge object.
CREATE TABLE IF NOT EXISTS v2_knowledge_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_id BIGINT NOT NULL REFERENCES v2_knowledge(id) ON DELETE RESTRICT,
  action TEXT NOT NULL CHECK (action IN ('edit', 'deactivate', 'restore', 'move')),
  before_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  after_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE v2_knowledge_history IS
  'Small audit snapshots for human Knowledge edits; raw evidence is not copied or changed.';

CREATE INDEX IF NOT EXISTS ix_v2_knowledge_history_knowledge
  ON v2_knowledge_history(knowledge_id, created_at DESC, id DESC);
