-- Phase 3.1 read-only internal QA: durable answer runs with evidence snapshots.
--
-- Additive only.  The Answer Service never writes to v2_knowledge,
-- v2_knowledge_sources, v2_raw_evidence, or any learning/inbox table; it only
-- INSERTs/UPDATEs rows here.  Evidence snapshots copy the Knowledge text,
-- applicability signals, and source excerpts actually used for an answer, so a
-- later Knowledge edit cannot rewrite what an old run was based on.
CREATE TABLE IF NOT EXISTS v2_answer_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key TEXT NOT NULL,
  question TEXT NOT NULL DEFAULT '',
  context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_hash TEXT NOT NULL DEFAULT '',
  execution_status TEXT NOT NULL DEFAULT 'started' CHECK (execution_status IN (
    'started', 'completed', 'failed'
  )),
  answer_status TEXT NOT NULL DEFAULT 'service_error' CHECK (answer_status IN (
    'answered', 'needs_clarification', 'unsupported', 'service_error'
  )),
  answer_text TEXT NOT NULL DEFAULT '',
  clarifying_question TEXT NOT NULL DEFAULT '',
  reason_code TEXT NOT NULL DEFAULT '',
  evidence_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
  retrieval_trace JSONB NOT NULL DEFAULT '{}'::jsonb,
  model TEXT NOT NULL DEFAULT '',
  prompt_version TEXT NOT NULL DEFAULT '',
  llm_requests INTEGER NOT NULL DEFAULT 0 CHECK (llm_requests >= 0),
  latency_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- One idempotency key maps to exactly one run.  The same key with a
  -- different question/context is rejected with 409 at the API layer; the
  -- request_hash column records the normalized payload for that comparison.
  UNIQUE (idempotency_key)
);

COMMENT ON TABLE v2_answer_runs IS
  'Phase 3.1 read-only internal QA runs; evidence snapshots are immutable copies of the cited Knowledge and sources.';
COMMENT ON COLUMN v2_answer_runs.request_hash IS
  'SHA-256 over the normalized question and context; same key with a different hash is a 409.';
COMMENT ON COLUMN v2_answer_runs.execution_status IS
  'Pipeline outcome: started before the model call, completed or failed after it. Technical failures never become clarification.';
COMMENT ON COLUMN v2_answer_runs.evidence_snapshot IS
  'Knowledge id, revision marker, text, applicability signals, and source excerpt/locator copied at answer time.';

CREATE INDEX IF NOT EXISTS ix_v2_answer_runs_created
  ON v2_answer_runs(created_at DESC, id DESC);
