-- Phase 3.2 correction -> Experience -> retest loop.
--
-- Additive only.  Experience stays inside v2_knowledge (unit_kind/
-- applicability/revision describe it); no second experience database is
-- created.  v2_answer_feedback records one engineer correction against one
-- answer run and doubles as the lightweight unresolved-gap queue read by the
-- Inbox.  v2_answer_runs gains retest linkage plus a human verdict; verdicts
-- are written by people, never by the answering model.

CREATE TABLE IF NOT EXISTS v2_answer_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_run_id BIGINT NOT NULL REFERENCES v2_answer_runs(id) ON DELETE RESTRICT,
  -- Client-generated per correction form; resubmits return the stored row.
  idempotency_key TEXT NOT NULL UNIQUE,
  feedback_kind TEXT NOT NULL CHECK (feedback_kind IN (
    'reply_only', 'save_experience', 'missing_information',
    'retrieval_failure', 'generation_failure',
    'field_result_success', 'field_result_failure'
  )),
  -- The engineer-edited correction or gap description.  Length is validated
  -- at the API layer; values here are never silently truncated.
  correction_text TEXT NOT NULL DEFAULT '',
  applicability JSONB NOT NULL DEFAULT '{}'::jsonb,
  unit_kind TEXT NOT NULL DEFAULT 'fact' CHECK (unit_kind IN (
    'fact', 'procedure', 'rule', 'experience'
  )),
  -- Explicit update target for save_experience.  Fixed at submit time; a
  -- confirm carrying a different target is rejected, never auto-merged.
  target_knowledge_id BIGINT REFERENCES v2_knowledge(id) ON DELETE SET NULL,
  expected_revision INTEGER,
  raw_evidence_id BIGINT REFERENCES v2_raw_evidence(id) ON DELETE SET NULL,
  proposal_id BIGINT REFERENCES v2_learning_proposals(id) ON DELETE SET NULL,
  knowledge_id BIGINT REFERENCES v2_knowledge(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
    'open', 'confirmed', 'closed'
  )),
  -- Field outcome for field_result_* kinds: 'success', 'failure', or NULL
  -- (unknown).  Unknown is never auto-filled as resolved.
  field_result TEXT CHECK (field_result IN ('success', 'failure')),
  reviewer_label TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE v2_answer_feedback IS
  'Phase 3.2 engineer corrections against answer runs; also the unresolved-gap queue. reply_only never touches Knowledge.';
COMMENT ON COLUMN v2_answer_feedback.idempotency_key IS
  'Same key resubmits the stored feedback row instead of creating a duplicate Experience.';
COMMENT ON COLUMN v2_answer_feedback.target_knowledge_id IS
  'Explicit Knowledge update target chosen at submit; confirm must match it and its expected_revision.';

CREATE INDEX IF NOT EXISTS ix_v2_answer_feedback_run
  ON v2_answer_feedback(answer_run_id, id DESC);
CREATE INDEX IF NOT EXISTS ix_v2_answer_feedback_status
  ON v2_answer_feedback(status, id DESC);

-- Knowledge content kinds and explicit applicability/revision.  Phase 3 uses
-- fact/experience; procedure/rule arrive with Phase 4 document units.
ALTER TABLE v2_knowledge
  ADD COLUMN IF NOT EXISTS unit_kind TEXT NOT NULL DEFAULT 'fact'
    CHECK (unit_kind IN ('fact', 'procedure', 'rule', 'experience')),
  ADD COLUMN IF NOT EXISTS applicability JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1
    CHECK (revision >= 1);

COMMENT ON COLUMN v2_knowledge.unit_kind IS
  'Reusable unit kind; Experience is a kind, not a second knowledge store.';
COMMENT ON COLUMN v2_knowledge.applicability IS
  'Explicit models/versions/regions/conditions; empty means unstated, never generic.';
COMMENT ON COLUMN v2_knowledge.revision IS
  'Bumped on every content/applicability/trust change; confirms carry an expected revision.';

-- Proposals carry the same unit metadata through the existing
-- pending/confirm flow; feedback confirmations reuse these rows.
ALTER TABLE v2_learning_proposals
  ADD COLUMN IF NOT EXISTS unit_kind TEXT NOT NULL DEFAULT 'fact'
    CHECK (unit_kind IN ('fact', 'procedure', 'rule', 'experience')),
  ADD COLUMN IF NOT EXISTS applicability JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1
    CHECK (revision >= 1);

-- Answer-feedback proposals are not part of any Inbox thread.
ALTER TABLE v2_learning_proposals
  ALTER COLUMN thread_id DROP NOT NULL;

-- Retest linkage and human verdicts on answer runs.  A retest is always a
-- new run row; old runs are never overwritten.
ALTER TABLE v2_answer_runs
  ADD COLUMN IF NOT EXISTS retest_of BIGINT
    REFERENCES v2_answer_runs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS feedback_id BIGINT
    REFERENCES v2_answer_feedback(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewer_verdict TEXT
    CHECK (reviewer_verdict IN ('pass', 'fail')),
  ADD COLUMN IF NOT EXISTS reviewer_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reviewer_label TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

COMMENT ON COLUMN v2_answer_runs.retest_of IS
  'The older run this run retests; set at insert, never updated.';
COMMENT ON COLUMN v2_answer_runs.reviewer_verdict IS
  'Human retest judgement (pass/fail); never written by the answering model.';

-- Confirmations are auditable Knowledge changes alongside edit/deactivate.
ALTER TABLE v2_knowledge_history
  DROP CONSTRAINT IF EXISTS v2_knowledge_history_action_check;
ALTER TABLE v2_knowledge_history
  ADD CONSTRAINT v2_knowledge_history_action_check CHECK (action IN (
    'edit', 'deactivate', 'restore', 'move', 'confirm'
  ));
