-- Phase 4.1 structured PDF/PPTX intake: file versions, structure blocks,
-- and background jobs.  V1 documents/document_chunks stay read-only; new V2
-- learning content never flows into the V1 retrieval tables.  Raw block text
-- lives in v2_raw_evidence (single editable-original store); blocks point at
-- it instead of duplicating content.  V2 document IDs never enter the old
-- V1 document_id/document_chunk_id FK columns.

CREATE TABLE IF NOT EXISTS v2_document_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Version group for one manual (never guessed from filenames).
  document_key TEXT NOT NULL,
  version_label TEXT NOT NULL DEFAULT '',
  sha256 TEXT NOT NULL,
  file_name TEXT NOT NULL DEFAULT '',
  file_type TEXT NOT NULL CHECK (file_type IN ('pdf', 'pptx')),
  file_size BIGINT NOT NULL DEFAULT 0 CHECK (file_size >= 0),
  -- Service-generated name under data/documents/v2/; the original filename
  -- is display-only and never touches the filesystem.
  stored_path TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  applicability JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_authenticity TEXT NOT NULL DEFAULT 'unverified' CHECK (
    source_authenticity IN ('unverified', 'official_vendor', 'confirmed_copy')
  ),
  parser_version TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'uploaded' CHECK (status IN (
    'uploaded', 'parsed', 'parse_failed', 'learning', 'complete',
    'learning_failed'
  )),
  legacy_document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (document_key, version_label)
);

COMMENT ON TABLE v2_document_versions IS
  'Phase 4.1 immutable file versions; bytes are never overwritten, new uploads become new rows.';
COMMENT ON COLUMN v2_document_versions.document_key IS
  'Human-chosen version group; never inferred from filenames.';

CREATE INDEX IF NOT EXISTS ix_v2_document_versions_sha
  ON v2_document_versions(sha256);
CREATE INDEX IF NOT EXISTS ix_v2_document_versions_status
  ON v2_document_versions(status, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS v2_document_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL REFERENCES v2_document_versions(id) ON DELETE CASCADE,
  block_key TEXT NOT NULL,
  parent_block_id BIGINT REFERENCES v2_document_blocks(id) ON DELETE SET NULL,
  ord INTEGER NOT NULL DEFAULT 0,
  section_path TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  page_no INTEGER,
  slide_no INTEGER,
  block_type TEXT NOT NULL CHECK (block_type IN (
    'heading', 'paragraph', 'table', 'list_item', 'image', 'caption',
    'note', 'other'
  )),
  raw_evidence_id BIGINT REFERENCES v2_raw_evidence(id) ON DELETE RESTRICT,
  content_hash TEXT NOT NULL DEFAULT '',
  -- Block geometry/assets: bbox, table cells with spans, image asset_ref +
  -- interpretation_status, speaker notes at slide level.  Never a second
  -- copy of the trusted text (that lives in raw evidence).
  layout JSONB NOT NULL DEFAULT '{}'::jsonb,
  assets JSONB NOT NULL DEFAULT '[]'::jsonb,
  processing_state TEXT NOT NULL DEFAULT 'pending' CHECK (processing_state IN (
    'pending', 'knowledge', 'proposal', 'evidence_only', 'needs_review',
    'parse_failed', 'learn_failed'
  )),
  state_reason TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (version_id, block_key)
);

COMMENT ON TABLE v2_document_blocks IS
  'Phase 4.1 structure map: every page/slide has an explicit processing destination; 100% processed means every block has one, never that all were understood.';
COMMENT ON COLUMN v2_document_blocks.raw_evidence_id IS
  'Block text lives in raw evidence; blocks never duplicate it. NULL for pure image blocks with no extractable text.';

CREATE INDEX IF NOT EXISTS ix_v2_document_blocks_version
  ON v2_document_blocks(version_id, ord, id);
CREATE INDEX IF NOT EXISTS ix_v2_document_blocks_state
  ON v2_document_blocks(version_id, processing_state);

CREATE TABLE IF NOT EXISTS v2_document_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL REFERENCES v2_document_versions(id) ON DELETE CASCADE,
  stage TEXT NOT NULL CHECK (stage IN ('parse', 'learn')),
  block_id BIGINT REFERENCES v2_document_blocks(id) ON DELETE SET NULL,
  checkpoint JSONB NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN (
    'queued', 'processing', 'completed', 'failed'
  )),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_run_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE v2_document_jobs IS
  'Phase 4.1 background steps with checkpoints and idempotent re-execution; one step never holds the worker for a whole manual.';

CREATE INDEX IF NOT EXISTS ix_v2_document_jobs_queue
  ON v2_document_jobs(status, next_run_at, id);

-- Per-version Knowledge linkage and validation gate.  NULL origin means a
-- pre-document row ruled by the old trust/source gate; document units need
-- validation_status='validated' before they may support answers (Phase 4.2).
ALTER TABLE v2_knowledge
  ADD COLUMN IF NOT EXISTS origin_document_version_id BIGINT
    REFERENCES v2_document_versions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS validation_status TEXT
    CHECK (validation_status IN ('pending', 'validated', 'needs_revalidation'));

COMMENT ON COLUMN v2_knowledge.origin_document_version_id IS
  'Document version this unit was learned from; NULL for pre-document rows. One version never shares a Knowledge row with another.';
COMMENT ON COLUMN v2_knowledge.validation_status IS
  'NULL for non-document rows; document units start pending and need explicit validation before answering.';
